name: Update Table of Contents

on:
  push:
    branches:
      - main
    paths:
      - "README.md"

jobs:
  update-toc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate TOC
        uses: technote-space/toc-generator@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_PATHS: README.md
          TOC_TITLE: "**Table of Contents**"
          COMMIT_MESSAGE: "Update Table of Contents [skip ci]"
