name: Update Table of Contents

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-toc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug - Check runner environment
        run: |
          echo "OS Info:"
          cat /etc/os-release
          echo "Shell Info:"
          ls -l /bin/sh || echo "/bin/sh not found"

      - name: Generate TOC
        uses: technote-space/toc-generator@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_PATHS: README.md
          TOC_TITLE: "**Table of Contents**"
          COMMIT_MESSAGE: "Update Table of Contents [skip ci]"

      - name: Debug - Check README.md after TOC generation
        run: cat README.md
